### ISSUE TITLE
Main page isn't updating current announcements

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#141]
cc @progwml6

**Comment by progwml6** [comment]
A restart was needed to cause updates to get to the homepage, busting the cache did not help.

Something needs to be written to check for new updates periodically and bust the cache when new ones are found

**Comment by stephan-gh** [comment]
Fastly should be configured to cache the announcements for up to one hour, then consult the backend server for updates.

However, it seems like something is wrong with the response headers - instead of replacing the static content cache configuration that we're using by default, it seems to add the `Surrogate-Control` header twice:

```
Surrogate-Control: max-age=3600, stale-while-revalidate=300, stale-if-error=604800
Surrogate-Control: max-age=2628000, stale-while-revalidate=300, stale-if-error=604800
```

If Fastly is using the last header, it would cache the announcements for up to a month, which is not what we want. Need to make sure the header is not added if it exists already.
